---
title: "201 final project"
output: html_document
date: "2023-11-29"
---

```{r}
library(dplyr)
library(tidyverse)
riskFactors <- read_delim("Data/Behavioral_Risk_Factors__Selected_Metropolitan_Area_Risk_Trends__SMART__MMSA_Prevalence_Data__2011_to_Present_.csv")

riskFactors %>% 
  head(25)

riskFactors <- riskFactors %>% 
  filter(Year == 2019) %>% 
  filter(Topic == "Cholesterol High" | Topic == "High Blood Pressure" | Topic == "Exercise" | Topic == "Current Smoker Status") %>% 
  summarise(Locationdesc, Question, Response, Data_value, Topic)

rfwExercise <- riskFactors %>% 
  filter(Topic == "Exercise") %>% 
  pivot_wider(names_from = "Response",
               values_from = "Data_value")

rfwCholesterol <- riskFactors %>% 
  filter(Topic == "Cholesterol High") %>% 
  pivot_wider(names_from = "Response",
               values_from = "Data_value")

rfwBP <- riskFactors %>% 
  filter(Topic == "High Blood Pressure") %>% 
  pivot_wider(names_from = "Response",
               values_from = "Data_value")

rfwSmoke <- riskFactors %>% 
  filter(Topic == "Current Smoker Status") %>% 
  pivot_wider(names_from = "Response",
               values_from = "Data_value")
```

```{r}
rfwAll <- rfwExercise %>%
  inner_join(rfwCholesterol, by="Locationdesc")

rfwAll <- rfwAll %>%
  inner_join(rfwBP, by="Locationdesc")

rfwAll <- rfwAll %>%
  inner_join(rfwSmoke, by="Locationdesc")

rfwAll
```


```{r}
heartDisease <- read_delim("Data/Rates_and_Trends_in_Heart_Disease_and_Stroke_Mortality_Among_US_Adults__35___by_County__Age_Group__Race_Ethnicity__and_Sex___2000-2019.csv")

heartDisease <- heartDisease %>% 
  filter(Year == 2019)
```

```{r}
colnames(heartDisease)[colnames(heartDisease) == 'Stratification1'] <- 'Age.group'
colnames(heartDisease)[colnames(heartDisease) == 'Stratification2'] <- 'Race'
colnames(heartDisease)[colnames(heartDisease) == 'Stratification3'] <- 'Sex'

heartDisease <- heartDisease %>% 
  filter(!is.na(Data_Value), Race == "Overall", Sex == "Overall") %>% 
  summarise(LocationDesc, LocationAbbr, Topic, Age.group, Race, Sex, Data_Value, Data_Value_Unit)

hdAllHeartDisease <- heartDisease %>% 
  filter(Topic == "All heart disease") %>% 
  pivot_wider(names_from = "Age.group",
               values_from = "Data_Value") %>% 
  unchop(everything())

colnames(hdAllHeartDisease)[colnames(hdAllHeartDisease) == 'Ages 35-64 years'] <- 'Ages_35_to_64_years'
colnames(hdAllHeartDisease)[colnames(hdAllHeartDisease) == 'Ages 65 years and older'] <- 'Ages_65_years_and_older'

hdAllHeartDisease
```

```{r}
matching <- read_delim("Data/metroToCounty.csv")

matching <- matching %>% 
  summarize(CSA.Title, CBSA.Title, Metropolitan.Micropolitan.Statistical.Area, County.County.Equivalent) %>% 
  mutate(title = ifelse(is.na(CSA.Title), CBSA.Title, CSA.Title)) %>% 
  mutate(stateMatching = sapply(strsplit(title,", "), `[`, 2)) %>% 
  mutate(title = paste(title, Metropolitan.Micropolitan.Statistical.Area)) %>% 
  summarize(title, County.County.Equivalent, stateMatching)

```

```{r}
intermediateExercise <- rfwExercise %>%
  inner_join(matching, by=c("Locationdesc"="title")) %>% 
  mutate(County.County.Equivalent = gsub("\\s*\\w*$", "", County.County.Equivalent))

finalExercise <- hdAllHeartDisease %>%
  inner_join(intermediateExercise, by=c("LocationDesc"="County.County.Equivalent"))

finalExerciseBrief <- finalExercise %>% 
  arrange(LocationDesc) %>% 
  filter(str_detect(stateMatching, LocationAbbr)) %>% 
  mutate(LocationID = paste(LocationDesc, " ", LocationAbbr, " :: ", Locationdesc)) %>% 
  summarise(LocationID, Question, Yes, No, Topic.x, Ages_35_to_64_years, Ages_65_years_and_older, Data_Value_Unit)

finalExerciseBrief

write.csv(finalExerciseBrief, "Data/heartDisease&Exercise.csv", row.names=FALSE)
```

```{r}
intermediateAll <- rfwAll %>%
  inner_join(matching, by=c("Locationdesc"="title")) %>% 
  mutate(County.County.Equivalent = gsub("\\s*\\w*$", "", County.County.Equivalent))

finalAll <- hdAllHeartDisease %>%
  inner_join(intermediateAll, by=c("LocationDesc"="County.County.Equivalent"))

finalAllBrief <- finalAll %>% 
  arrange(LocationDesc) %>% 
  filter(str_detect(stateMatching, LocationAbbr)) %>% 
  mutate(LocationID = paste(LocationDesc, " ", LocationAbbr, " :: ", Locationdesc)) %>% 
  summarise(LocationID, Topic, Ages_35_to_64_years, Ages_65_years_and_older, Data_Value_Unit,
            Question.x, Yes.x, No.x, 	
            Question.y, Yes.y, No.y,
            Question.x.x, Yes.x.x, No.x.x,
            Question.y.y, Yes.y.y, No.y.y)

colnames(finalAllBrief)[colnames(finalAllBrief) == 'Question.x'] <- 'Question_1'
colnames(finalAllBrief)[colnames(finalAllBrief) == 'Question.y'] <- 'Question_2'
colnames(finalAllBrief)[colnames(finalAllBrief) == 'Question.x.x'] <- 'Question_3'
colnames(finalAllBrief)[colnames(finalAllBrief) == 'Question.y.y'] <- 'Question_4'

colnames(finalAllBrief)[colnames(finalAllBrief) == 'Yes.x'] <- 'Yes_1'
colnames(finalAllBrief)[colnames(finalAllBrief) == 'Yes.y'] <- 'Yes_2'
colnames(finalAllBrief)[colnames(finalAllBrief) == 'Yes.x.x'] <- 'Yes_3'
colnames(finalAllBrief)[colnames(finalAllBrief) == 'Yes.y.y'] <- 'Yes_4'

colnames(finalAllBrief)[colnames(finalAllBrief) == 'No.x'] <- 'No_1'
colnames(finalAllBrief)[colnames(finalAllBrief) == 'No.y'] <- 'No_2'
colnames(finalAllBrief)[colnames(finalAllBrief) == 'No.x.x'] <- 'No_3'
colnames(finalAllBrief)[colnames(finalAllBrief) == 'No.y.y'] <- 'No_4'

finalAllBrief <- finalAllBrief %>% 
  mutate(Question_1 = "During the past month, did you participate in any physical activities?") %>% 
  mutate(Question_2 = "Adults who have had their blood cholesterol checked and have been told it was high") %>% 
  mutate(Question_3 = "Adults who have been told they have high blood pressure") %>% 
  mutate(Question_4 = "Adults who are current smokers")

finalAllBrief

write.csv(finalAllBrief, "Data/heartDisease&RiskFactors.csv", row.names=FALSE)
```











